export const data = [{
        id: 1,
        img: "https://images.unsplash.com/photo-1614724723656-457e78e0b50b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bWVyY3VyeXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=400&q=60",
        planet: "Mercury",
        info: "The smallest planet in our solar system and nearest to the Sun, Mercury is only slightly larger than Earth's Moon. From the surface of Mercury, the Sun would appear more than three times as large as it does when viewed from Earth, and the sunlight would be as much as seven times brighter. Despite its proximity to the Sun, Mercury is not the hottest planet in our solar system – that title belongs to nearby Venus, thanks to its dense atmosphere.",
        link: "https://solarsystem.nasa.gov/planets/mercury/overview/",
    },
    {
        id: 2,
        img: "https://images.unsplash.com/photo-1590907043334-8eba76905b92?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8dmVudXMlMjBwbGFuZXR8ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60",
        planet: "Venus",
        info: "Venus is the second planet from the Sun and is Earth’s closest planetary neighbor. It’s one of the four inner, terrestrial (or rocky) planets, and it’s often called Earth’s twin because it’s similar in size and density. These are not identical twins, however – there are radical differences between the two worlds.",
        link: "https://solarsystem.nasa.gov/planets/venus/overview/",
    },
    {
        id: 3,
        img: "https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fHZlbnVzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=400&q=60",
        planet: "Earth",
        info: "Our home planet is the third planet from the Sun, and the only place we know of so far that’s inhabited by living things. While Earth is only the fifth largest planet in the solar system, it is the only world in our solar system with liquid water on the surface. Just slightly larger than nearby Venus, Earth is the biggest of the four planets closest to the Sun, all of which are made of rock and metal.",
        link: "https://solarsystem.nasa.gov/planets/earth/overview/",
    },
    {
        id: 4,
        img: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8dmVudXN8ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60",
        planet: "Mars",
        info: "​Mars is the fourth planet from the Sun – a dusty, cold, desert world with a very thin atmosphere. Mars is also a dynamic planet with seasons, polar ice caps, canyons, extinct volcanoes, and evidence that it was even more active in the past. Mars is one of the most explored bodies in our solar system, and it's the only planet where we've sent rovers to roam the alien landscape",
        link: "https://solarsystem.nasa.gov/planets/mars/overview/",
    },
    {
        id: 5,
        img: "https://images.unsplash.com/photo-1614314169000-4cf229a1db33?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8dmVudXMlMjBwbGFuZXR8ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60",
        planet: "Jupiter",
        info: "Jupiter has a long history of surprising scientists – all the way back to 1610 when Galileo Galilei found the first moons beyond Earth. That discovery changed the way we see the universe. Fifth in line from the Sun, Jupiter is, by far, the largest planet in the solar system – more than twice as massive as all the other planets combined.",
        link: "https://solarsystem.nasa.gov/planets/jupiter/overview/",
    },
    {
        id: 6,
        img: "https://images.unsplash.com/photo-1614732414444-096e5f1122d5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8dmVudXN8ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60",
        planet: "Saturn",
        info: "Saturn is the sixth planet from the Sun and the second-largest planet in our solar system. Adorned with thousands of beautiful ringlets, Saturn is unique among the planets. It is not the only planet to have rings – made of chunks of ice and rock – but none are as spectacular or as complicated as Saturn's. ",
        link: "https://solarsystem.nasa.gov/planets/saturn/overview/",
    },
    {
        id: 7,
        img: "https://images.unsplash.com/photo-1614732484003-ef9881555dc3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjB8fHZlbnVzJTIwcGxhbmV0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=400&q=60",
        planet: "Uranus",
        info: "Uranus is the seventh planet from the Sun, and has the third-largest diameter in our solar system. It was the first planet found with the aid of a telescope, Uranus was discovered in 1781 by astronomer William Herschel, although he originally thought it was either a comet or a star.",
        link: "https://solarsystem.nasa.gov/planets/uranus/overview/",
    },
    {
        id: 8,
        img: "https://images.unsplash.com/photo-1614728423169-3f65fd722b7e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8dmVudXN8ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60",
        planet: "Neptune",
        info: "Dark, cold, and whipped by supersonic winds, ice giant Neptune is the eighth and most distant planet in our solar system. More than 30 times as far from the Sun as Earth, Neptune is the only planet in our solar system not visible to the naked eye and the first predicted by mathematics before its discovery. In 2011 Neptune completed its first 165-year orbit since its discovery in 1846.",
        link: "https://solarsystem.nasa.gov/planets/neptune/overview/",
    },
];